products: list[dict] = [
    {"id": 1, "name": "Whole Milk 1L", "category": "dairy", "price": 38000},
    {"id": 2, "name": "Low Fat Milk 1L", "category": "dairy", "price": 36000},
    {"id": 3, "name": "Greek Yogurt 500g", "category": "dairy", "price": 72000},
    {"id": 4, "name": "Cheddar Cheese 250g", "category": "dairy", "price": 145000},
    {"id": 5, "name": "Butter 100g", "category": "dairy", "price": 54000},
    {"id": 6, "name": "Sourdough Bread", "category": "bakery", "price": 60000},
    {"id": 7, "name": "Whole Wheat Bread", "category": "bakery", "price": 48000},
    {"id": 8, "name": "Croissant", "category": "bakery", "price": 32000},
    {"id": 9, "name": "Chocolate Muffin", "category": "bakery", "price": 41000},
    {"id": 10, "name": "Red Apple 1kg", "category": "fruit", "price": 95000},
    {"id": 11, "name": "Banana 1kg", "category": "fruit", "price": 78000},
    {"id": 12, "name": "Orange 1kg", "category": "fruit", "price": 88000},
    {"id": 13, "name": "Green Grape 1kg", "category": "fruit", "price": 130000},
    {"id": 14, "name": "Strawberry 500g", "category": "fruit", "price": 160000},
    {"id": 15, "name": "Sparkling Water 1.5L", "category": "drinks", "price": 28000},
    {"id": 16, "name": "Orange Juice 1L", "category": "drinks", "price": 95000},
    {"id": 17, "name": "Cola 1.5L", "category": "drinks", "price": 42000},
    {"id": 18, "name": "Green Tea Box", "category": "drinks", "price": 110000},
    {"id": 19, "name": "Potato Chips 150g", "category": "snacks", "price": 55000},
    {"id": 20, "name": "Salted Peanuts 200g", "category": "snacks", "price": 68000},
    {"id": 21, "name": "Dark Chocolate Bar", "category": "snacks", "price": 85000},
    {"id": 22, "name": "Rice Crackers", "category": "snacks", "price": 47000},
]
